name: CI of all packages
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Install dependencies
        run: npm ci
      - name: CI checks
        run: |
          npm run build
          npm run test

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
