name: Tests
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Run tests
        run: npm run test -- --coverage

      - uses: codecov/codecov-action@v2
        with:
          directory: ./coverage
          flags: summary
          name: demo

concurrency:
  group: test-${{ github.head_ref }}
  cancel-in-progress: true
